seasons:
- 2020
- 2021
- 2022
- 2023
- 2024
weeks:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
targets:
- home_points
- away_points
league_avg_points: 22.0
home_field_points: 1.5
rolling_window_weeks: 3
ewm_alpha: 0.3
min_plays_team_week: 20
poisson_objective: true
random_seed: 42
